
services:
  web:
    build: .
    ports:
      - "8104:5000"
    environment:
      DB_HOST: db
      DB_PORT: 3307
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: todo_db
    depends_on:
      - db
    networks:
      - todo-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
      - "3308:3307"
      - "3309:3308"
      - "3310:3309"
      - "3311:3310"
      - "3312:3311"
    networks:
      - todo-net
    command: --port=3307
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  todo-net:
