name: Deploy Flask App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build imagem
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-app .

    - name: Push imagem
      run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy remoto
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 201.23.3.86
        username: aluno
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop todo-app || true
          docker rm todo-app || true
          docker stop todo-db || true
          docker rm todo-db || true
          docker run -d --name todo-db -e MYSQL_ROOT_PASSWORD=rootpass -e MYSQL_DATABASE=todo_db -e MYSQL_USER=user -e MYSQL_PASSWORD=password -p 3307:3306 -p 3308:3307 -p 3309:3308 -p 3310:3309 -p 3311:3310 -p 3312:3311 mysql:8.0 --port=3307
          sleep 30
          docker pull ${{ secrets.DOCKER_USERNAME }}/todo-app
          docker run -d --name todo-app --link todo-db:db -p 8104:5000 -p 8105:5001 -p 8106:5002 -p 8107:5003 -p 8108:5004 -p 8109:5005 -e DB_HOST=db -e DB_PORT=3307 -e DB_USER=user -e DB_PASSWORD=password -e DB_NAME=todo_db ${{ secrets.DOCKER_USERNAME }}/todo-app
